on: 
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
    test:
        runs-on: codeberg-tiny
        container:
            image: registry.access.redhat.com/ubi10:latest
        steps:
            - name: Make request
              run: curl -XPOST -s ${{secrets.WEBHOOK}} > /dev/null