on: 
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
    test:
        runs-on: codeberg-tiny
        container:
            image: ghcr.io/almalinux/almalinux:9
        steps:
            - name: Make request
              run: curl -XPOST -L -s "${{secrets.WEBHOOK}}" > /dev/null