name: Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: Build the image
      run: podman build -t ghcr.io/charles25565/minimalrootfs .
    - name: Push the image
      run: podman push ghcr.io/charles25565/minimalrootfs